In [1]:
#Esercizio 1 • Valori nulli 
#Dati: un DataFrame clienti con colonne nome, eta e citta per 8 righe, costruito con un dizionario di liste.

#1. costruire il DataFrame clienti con le tre colonne, 
#inserendo almeno tre valori nulli (None) in totale, non tutti sulla stessa colonna.

import pandas as pd #creo un df con 3 none

Clienti = pd.DataFrame({
    "nome" : [None, "Verdi", "Gialli", "Bianchi", "Arancio", "Viola", "Blu", "Rosa"],
    "eta" : [35, 47, 22, 55, None, 33, 70, 42],
    "citta": ["Milano", "Bologna", "Modena", "Torino", "Palermo", "Catania", None, "Napoli"]
})

Clienti

      nome   eta    citta
0      NaN  35.0   Milano
1    Verdi  47.0  Bologna
2   Gialli  22.0   Modena
3  Bianchi  55.0   Torino
4  Arancio   NaN  Palermo
5    Viola  33.0  Catania
6      Blu  70.0      NaN
7     Rosa  42.0   Napoli

In [6]:
#2. usare .isna() sull'intero DataFrame e poi .isna().sum() per contare i valori nulli in ciascuna colonna.

import pandas as pd

Clienti.isna() #mi dice true se ci sono dei none, false se tutti i valori sono presenti

Clienti.isna().sum() #mi fa la somma totale dei true trovati

nome     1
eta      1
citta    1
dtype: int64

In [8]:

#3. usare .dropna() per ottenere un nuovo DataFrame senza righe con valori nulli, 
#assegnando il risultato a una nuova variabile

import pandas as pd

Clienti_drop = Clienti.dropna() #elimino tutte le righe in cui erano presenti dei none (true)

Clienti_drop

      nome   eta    citta
1    Verdi  47.0  Bologna
2   Gialli  22.0   Modena
3  Bianchi  55.0   Torino
5    Viola  33.0  Catania
7     Rosa  42.0   Napoli

In [ ]:
#Definizione richiesta: scrivere la definizione di valore nullo in Pandas 
#e spiegare perché .dropna() non modifica il DataFrame originale.

#In Pandas un valore nullo è un osservazione mancata o non disponibile all'interno di una cella di un data frame
#.dropna() non modifica il dataframe originale, in quanto, assegnandolo a una nuova variabile, 
#restituisce un nuovo dataframe, diverso dall'orginiale, con i null assanti. 

#Criterio di completamento: il conteggio per colonna di .isna().sum() corrisponde ai nulli inseriti al punto 1, 
#e il DataFrame ottenuto con dropna() ha meno righe di quello originale.

In [12]:
#Esercizio 2 • Ordinamento 
#Dati: un DataFrame prodotti con colonne nome, categoria e prezzo per 6 prodotti di almeno due categorie diverse.


#1. ordinare il DataFrame per la colonna prezzo in ordine decrescente con .sort_values(), 
#assegnando il risultato a una nuova variabile.

import pandas as pd #creo un nuovo df Prodotti

Prodotti = pd.DataFrame({
    "nome" : ["caffettiera", "bollitore", "padella", "pentola", "bicchieri", "microonde"],
    "categoria" : ["pentolame", "elettrodomestici", "pentolame", "pentolame", "stoviglie", "elettrodomestici"],
    "prezzo": [20, 40, 35, 60, 15, 100]
})

Prodotti

Prodotti_ord = Prodotti.sort_values("prezzo") #rinomino la variabile e ordino in base alla colonna "prezzo"

Prodotti_ord

          nome         categoria  prezzo
4    bicchieri         stoviglie      15
0  caffettiera         pentolame      20
2      padella         pentolame      35
1    bollitore  elettrodomestici      40
3      pentola         pentolame      60
5    microonde  elettrodomestici     100

In [18]:
#2. ordinare il DataFrame passando una lista di due colonne a sort_values(): 
#prima categoria in ordine crescente, poi prezzo in ordine decrescente.

import pandas as pd

Prodotti_or = Prodotti.sort_values(["categoria", "prezzo"], ascending = [True, False]) 
#ordinamento in base a cateforia e prezzo, il primo crescente, quindi true, il secondo decrescente, quindi false
Prodotti_or

          nome         categoria  prezzo
5    microonde  elettrodomestici     100
1    bollitore  elettrodomestici      40
3      pentola         pentolame      60
2      padella         pentolame      35
0  caffettiera         pentolame      20
4    bicchieri         stoviglie      15

In [ ]:
#3. confrontare le prime due righe dei risultati dei punti 1 e 2 e spiegare perché sono diverse.

#Sono diverse perché nella prima abbiamo ordinato soltanto per prezzo, dal meno caro al più caro, 
#nella seconda abbiamo ordinato in modo crescente anche per categoria e poi ordinato anche per prezzo dal più caro al meno

In [19]:
#Definizione richiesta: scrivere la definizione di ordinamento su più colonne e spiegare a cosa serve il parametro ascending
#quando riceve una lista.

#l'ordinamento è un metodo che permette di ordinare le righe  sulla base dei valori di una o più colonne
#il paramentro ascending ordina di default (quando è true) in modo crescente; con false è ordinamento decrescente

#Criterio di completamento: sono stampati entrambi i DataFrame ordinati, 
#e la differenza tra i due ordinamenti al punto 3 è motivata in una frase.

In [37]:
#Esercizio 3 • Filtri con condizioni multiple
#Dati: il DataFrame prodotti dell'esercizio precedente, o uno equivalente con almeno 6 righe e una colonna categoria.

#1. costruire un filtro che selezioni i prodotti con prezzo superiore a una soglia a scelta 
#e categoria uguale a un valore a scelta, combinando le due condizioni con l'operatore &.

import pandas as pd #df Prodotti

Prodotti = pd.DataFrame({
    "nome" : ["caffettiera", "bollitore", "padella", "pentola", "bicchieri", "microonde"],
    "categoria" : ["pentolame", "elettrodomestici", "pentolame", "pentolame", "stoviglie", "elettrodomestici"],
    "prezzo": [20, 40, 35, 60, 15, 100]
})

Prodotti

condizione_prezzo = Prodotti["prezzo"] > 30
condizione_categoria = Prodotti["categoria"] == "pentolame"

filtro_prodotti = Prodotti.loc[condizione_prezzo & condizione_categoria]

print(filtro_prodotti)

      nome  categoria  prezzo
2  padella  pentolame      35
3  pentola  pentolame      60

In [38]:
#2. usare .isin() per selezionare i prodotti che appartengono a una lista di due categorie a scelta, senza scrivere due condizioni
#unite da |. 

import pandas as pd

Prodotti[Prodotti["categoria"].isin(["pentolame", "stoviglie"])]

          nome  categoria  prezzo
0  caffettiera  pentolame      20
2      padella  pentolame      35
3      pentola  pentolame      60
4    bicchieri  stoviglie      15

In [39]:
#3. negare il filtro del punto 2 con l'operatore ~ per ottenere i prodotti che non appartengono a quelle categorie.

import pandas as pd

Prodotti[~Prodotti["categoria"].isin(["pentolame", "stoviglie"])]

Prodotti[]

        nome         categoria  prezzo
1  bollitore  elettrodomestici      40
5  microonde  elettrodomestici     100

In [42]:
#Definizione richiesta: scrivere la definizione di .isin() e spiegare perché in Pandas si usano & e | 
#invece di and e or per combinare condizioni.

#.isin() è un metodo che verifica se ogni valore di una colonna è presente nella lista data
#In Pandas gli operatori logici & e \ sono equivalenti a and e or che si usano solo in Python puro

#Criterio di completamento: sono stampati i risultati dei tre filtri, 
#e la somma delle righe dei filtri dei punti 2 e 3 corrisponde al numero totale di righe del DataFrame.

condizione_prodotti = Prodotti["categoria"].isin(["pentolame", "stoviglie"]) #lo verifico tramite Len

filtro = Prodotti.loc[condizione_prodotti]
filtro_tilde = Prodotti.loc[~condizione_prodotti]

print(len(filtro) + len(filtro_tilde))   # 6
print(len(Prodotti))                      # 6
print(len(filtro) + len(filtro_tilde) == len(Prodotti))

6
6
True

In [57]:
#Esercizio 4 • Strategie di imputazione
#Dati: una Series temperature con sei valori, di cui uno nullo in posizione intermedia, ad esempio (20, 21, None, 24, 25, 23].

#1. applicare separatamente fillna() con un valore fisso a scelta, ffill() e .interpolate() 
#alla stessa Series, ottenendo tre risultati distinti.

import pandas as pd

temperature = pd.Series([20, 21, None, 24, 25, 23])

temperature

print(temperature.ffill()) #valore precedente, 21
print(temperature.fillna(28))#valore fisso, 28
print(temperature.bfill())  #24 il valore successivo disponibile
print(temperature.interpolate()) #22.5 fa la media, interpolazione

0    20.0
1    21.0
2    21.0
3    24.0
4    25.0
5    23.0
dtype: float64
0    20.0
1    21.0
2    28.0
3    24.0
4    25.0
5    23.0
dtype: float64
0    20.0
1    21.0
2    24.0
3    24.0
4    25.0
5    23.0
dtype: float64
0    20.0
1    21.0
2    22.5
3    24.0
4    25.0
5    23.0
dtype: float64

In [54]:
#3. indicare, per un caso in cui il valore nullo fosse il primo elemento della Series invece che uno intermedio, 
#quale dei quattro metodi non riuscirebbe a riempirlo, motivando la risposta.


import pandas as pd

temperature = pd.Series([None, 21, 22, 24, 25, 23])

temperature

print(temperature.ffill()) # ffill non riesce a riempirlo perché consindere il valore precedente per riempire il gap
# non essendoci un valore precedente, non riesce e dare un valore al primo elemento della series

print(temperature.interpolate()) #anche interpolate perché lui stima un punto intermedio  tra il precedente e il successivo
#essendo il primo, non può lavorare e dunque non riesce a riempire il gap, rimanendo None

0     NaN
1    21.0
2    22.0
3    24.0
4    25.0
5    23.0
dtype: float64
0     NaN
1    21.0
2    22.0
3    24.0
4    25.0
5    23.0
dtype: float64

In [ ]:
#Definizione richiesta: scrivere la definizione di imputazione 
#e spiegare la differenza concettuale tra un valore imputato con .fillna() e uno stimato con interpolate().

#L'imputazione è la sostituzione dei valori mancanti di un dataset con valori stimati o scelti
#la scelta avviena appunto, con diversi metodi. .fillna() inserisce un valore FISSO scelto, 
#mentre Interpolate fa una un calcolo di un punto intermedio tra i valori che precedono e seguono. Non lavora sempre, tuttavia.


#Criterio di completamento: sono stampati i quattro risultati (fillna, fill, bfill, interpolate) 
#applicati alla stessa Series originale, e la risposta del punto 3 indica un metodo con la relativa motivazione.